### ISSUE TITLE
拉库拉不了,github和gitee的脚本都无法

### ISSUE THREAD

**Issue by kaichenglei** [xiaoxiaofeixf/qinglong#2]
![image](https://user-images.githubusercontent.com/47828226/149744891-b837ca5e-2828-41ca-bbba-240d5a89faaa.png)

**Comment by xiaoxiaofeixf** [comment]
> ![image](https://user-images.githubusercontent.com/47828226/149744891-b837ca5e-2828-41ca-bbba-240d5a89faaa.png)

等待修复，建议用oketo容器
